### Biblioteki

In [ ]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt

In [ ]:

from src.data.utils import create_dataframe_from_csv_zst

from src.data.utils import create_dataframe_from_csv_zst
from src.features.clean_column_names import clean_column_names

### Finałowy dataset

In [3]:
AMENITIES_PATH = "../data/processed/amenities_stats.csv.zst"
REVIEWS_STATISTICS_PATH = "../data/processed/merged_reviews_statistics.csv.zst"
LISTINGS_PATH = "../data/raw/v2/listings.csv.zst"
SESSIONS_STATISTICS_PATH = "../data/processed/listings_statistics.csv"

In [4]:
amenities_df = create_dataframe_from_csv_zst(AMENITIES_PATH)
reviews_statistics_df = create_dataframe_from_csv_zst(REVIEWS_STATISTICS_PATH)
listings_df = create_dataframe_from_csv_zst(LISTINGS_PATH)

/home/psik/GITHUB/IUM/IUM-long-stay-insights/src/data/utils.py:13: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [5]:
amenities_df.head(5)

,id,amenities,standardized_amenities,num_of_amenities,num_of_other_amenities,has_wifi,has_air_conditioning,num_of_top_10_common_amenities,mean_embedding
0,27262,"[""Heating - split type ductless system"", ""Dish...","['OTHER', 'OTHER', 'OTHER', 'OTHER', 'Refriger...",37,25,True,False,9,[-6.15361333e-02 -5.01407236e-02 -3.76954190e-...
1,809874,"[""Host greets you"", ""Dishes and silverware"", ""...","['OTHER', 'OTHER', 'Washer', 'TV', 'OTHER', 'R...",21,12,True,True,7,[-5.95615655e-02 -3.39257978e-02 -3.55266146e-...
2,866381,"[""Coffee"", ""Dishes and silverware"", ""Washer"", ...","['Coffee maker', 'OTHER', 'Washer', 'Condition...",49,29,True,True,12,[-5.62126637e-02 -3.99859361e-02 -3.53127755e-...
3,886724,"[""Host greets you"", ""Luggage dropoff allowed"",...","['OTHER', 'OTHER', 'Washer', 'OTHER', 'OTHER',...",20,13,True,True,6,[-5.84196560e-02 -4.62852195e-02 -3.04865874e-...
4,896212,"[""Host greets you"", ""Coffee"", ""Dishes and silv...","['OTHER', 'Coffee maker', 'OTHER', 'OTHER', 'O...",45,31,True,True,9,[-5.81393391e-02 -4.77810428e-02 -4.26256545e-...

In [6]:
reviews_statistics_df.head(5)

,listing_id,total_reviews,total_english_reviews,count_negative_english,count_positive_english
0,21853,33,17.0,1.0,16.0
1,27262,29,17.0,0.0,17.0
2,30320,172,133.0,15.0,118.0
3,30959,8,4.0,0.0,4.0
4,33945,78,60.0,2.0,58.0

In [7]:
listings_df.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d
0,27262,https://www.nocarz.pl/rooms/27262,20241225065837,2024-12-25,city scrape,"AQA-No7, Great mattress, high speed internet",THE MATTRESS - KING KOIL - Camden Luxury 160x2...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,37177,...,t,1,1,0,0,0.19,NaN,NaN,NaN,NaN
1,809874,https://www.nocarz.pl/rooms/809874,20241225065837,2024-12-25,city scrape,Wonderfull Penthouse!!,NaN,NaN,https://a0.muscache.com/pictures/11813063/7d06...,4259738,...,f,1,1,0,0,0.68,NaN,NaN,NaN,NaN
2,866381,https://www.nocarz.pl/rooms/866381,20241225065837,2024-12-25,city scrape,Acropolis View Funky House,Welcome to a colorful 7th-floor penthouse in N...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,4551671,...,f,1,1,0,0,0.28,NaN,NaN,NaN,NaN
3,886724,https://www.nocarz.pl/rooms/886724,20241225065837,2024-12-25,city scrape,Luxury Boutique Appartment -Athens,NaN,The apartment is very conveniently located for...,https://a0.muscache.com/pictures/14659524/b33a...,4700824,...,f,1,1,0,0,0.14,NaN,NaN,NaN,NaN
4,896212,https://www.nocarz.pl/rooms/896212,20241225065837,2024-12-25,city scrape,Living like in a cottage in the center of Athens,An oasis of calm in the centre of a crowded ci...,Exarchia is considered the bohemian and altern...,https://a0.muscache.com/pictures/prohost-api/H...,4777984,...,t,13,13,0,0,3.58,NaN,NaN,NaN,NaN

In [8]:
listings_df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d'],
      dtype='object')

In [9]:
interesting_columns = [
    'id',
    'host_is_superhost',
    'host_verifications',
    'host_acceptance_rate',
    'neighbourhood_cleansed',
    'latitude',
    'longitude',
    'property_type',
    'room_type',
    'accommodates',
    'bathrooms',
    'bathrooms_text',
    'bedrooms',
    'beds',
    'price',
    'license',
    'review_scores_rating',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_checkin',
    'review_scores_communication',
    'review_scores_location',
    'review_scores_value',
    'instant_bookable',
    'reviews_per_month',
    'availability_eoy',
    'number_of_reviews_ly'
]

In [10]:
final_df = listings_df[interesting_columns].copy()
final_df.head(5)

,id,host_is_superhost,host_verifications,host_acceptance_rate,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month,availability_eoy,number_of_reviews_ly
0,27262,t,"['email', 'phone']",100%,ΑΜΠΕΛΟΚΗΠΟΙ,37.98924,23.76500,Entire rental unit,Entire home/apt,2,...,4.89,4.90,4.86,4.97,4.75,4.71,t,0.19,NaN,NaN
1,809874,f,"['email', 'phone']",96%,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,37.96215,23.72179,Entire rental unit,Entire home/apt,4,...,4.97,4.97,4.89,4.92,4.86,4.91,f,0.68,NaN,NaN
2,866381,t,"['email', 'phone', 'work_email']",97%,ΝΕΟΣ ΚΟΣΜΟΣ,37.95523,23.72443,Entire condo,Entire home/apt,3,...,4.98,4.98,4.93,4.93,4.73,4.90,f,0.28,NaN,NaN
3,886724,f,['email'],0%,ΚΥΨΕΛΗ,37.99745,23.73973,Entire rental unit,Entire home/apt,2,...,4.88,4.47,4.88,4.89,4.28,4.72,f,0.14,NaN,NaN
4,896212,t,"['email', 'phone']",100%,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.98844,23.73845,Entire rental unit,Entire home/apt,2,...,4.94,4.96,4.97,4.93,4.82,4.93,t,3.58,NaN,NaN

In [11]:
listings_statistics = pd.read_csv(SESSIONS_STATISTICS_PATH)
listings_statistics.head(5)

,listing_id,total_bookings,total_duration,avg_duration,min_duration,max_duration,num_of_short_stays,num_of_long_stays
0,21853.0,33,48,1.454545,1,4,33,0
1,27262.0,29,144,4.965517,2,7,29,0
2,30320.0,172,360,2.093023,1,4,172,0
3,30959.0,8,12,1.500000,1,3,8,0
4,33945.0,78,540,6.923077,3,10,54,24

In [12]:
listings_statistics['target'] = np.where(
    listings_statistics['num_of_short_stays'] > listings_statistics['num_of_long_stays'],
    'short',
    'long'
)

In [13]:
listings_statistics.head()

,listing_id,total_bookings,total_duration,avg_duration,min_duration,max_duration,num_of_short_stays,num_of_long_stays,target
0,21853.0,33,48,1.454545,1,4,33,0,short
1,27262.0,29,144,4.965517,2,7,29,0,short
2,30320.0,172,360,2.093023,1,4,172,0,short
3,30959.0,8,12,1.500000,1,3,8,0,short
4,33945.0,78,540,6.923077,3,10,54,24,short

In [14]:
listing_statistics_final_df = listings_statistics[['listing_id','total_bookings', 'target']].copy()

In [15]:
listing_statistics_final_df.head(5)

   listing_id  total_bookings target
0     21853.0              33  short
1     27262.0              29  short
2     30320.0             172  short
3     30959.0               8  short
4     33945.0              78  short

### Złączenie datasetów

In [16]:
final_df = final_df.merge(
    listing_statistics_final_df,
    left_on='id',
    right_on='listing_id',
    how='left'
)
final_df.head(5)

,id,host_is_superhost,host_verifications,host_acceptance_rate,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month,availability_eoy,number_of_reviews_ly,listing_id,total_bookings,target
0,27262,t,"['email', 'phone']",100%,ΑΜΠΕΛΟΚΗΠΟΙ,37.98924,23.76500,Entire rental unit,Entire home/apt,2,...,4.97,4.75,4.71,t,0.19,NaN,NaN,27262.0,29.0,short
1,809874,f,"['email', 'phone']",96%,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,37.96215,23.72179,Entire rental unit,Entire home/apt,4,...,4.92,4.86,4.91,f,0.68,NaN,NaN,809874.0,97.0,short
2,866381,t,"['email', 'phone', 'work_email']",97%,ΝΕΟΣ ΚΟΣΜΟΣ,37.95523,23.72443,Entire condo,Entire home/apt,3,...,4.93,4.73,4.90,f,0.28,NaN,NaN,866381.0,40.0,long
3,886724,f,['email'],0%,ΚΥΨΕΛΗ,37.99745,23.73973,Entire rental unit,Entire home/apt,2,...,4.89,4.28,4.72,f,0.14,NaN,NaN,886724.0,18.0,short
4,896212,t,"['email', 'phone']",100%,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.98844,23.73845,Entire rental unit,Entire home/apt,2,...,4.93,4.82,4.93,t,3.58,NaN,NaN,896212.0,515.0,long

In [17]:
final_df= final_df.merge(
    reviews_statistics_df,
    left_on='id',
    right_on='listing_id',
    how='left'
)
final_df.head(5)

,id,host_is_superhost,host_verifications,host_acceptance_rate,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,availability_eoy,number_of_reviews_ly,listing_id_x,total_bookings,target,listing_id_y,total_reviews,total_english_reviews,count_negative_english,count_positive_english
0,27262,t,"['email', 'phone']",100%,ΑΜΠΕΛΟΚΗΠΟΙ,37.98924,23.76500,Entire rental unit,Entire home/apt,2,...,NaN,NaN,27262.0,29.0,short,27262.0,29.0,17.0,0.0,17.0
1,809874,f,"['email', 'phone']",96%,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,37.96215,23.72179,Entire rental unit,Entire home/apt,4,...,NaN,NaN,809874.0,97.0,short,809874.0,97.0,82.0,0.0,82.0
2,866381,t,"['email', 'phone', 'work_email']",97%,ΝΕΟΣ ΚΟΣΜΟΣ,37.95523,23.72443,Entire condo,Entire home/apt,3,...,NaN,NaN,866381.0,40.0,long,866381.0,40.0,31.0,0.0,31.0
3,886724,f,['email'],0%,ΚΥΨΕΛΗ,37.99745,23.73973,Entire rental unit,Entire home/apt,2,...,NaN,NaN,886724.0,18.0,short,886724.0,18.0,17.0,1.0,16.0
4,896212,t,"['email', 'phone']",100%,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.98844,23.73845,Entire rental unit,Entire home/apt,2,...,NaN,NaN,896212.0,515.0,long,896212.0,515.0,423.0,3.0,420.0

In [18]:
final_df = final_df.merge(
    amenities_df,
    left_on='id',
    right_on='id',
    how='left'
)
final_df.head(5)

,id,host_is_superhost,host_verifications,host_acceptance_rate,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,count_negative_english,count_positive_english,amenities,standardized_amenities,num_of_amenities,num_of_other_amenities,has_wifi,has_air_conditioning,num_of_top_10_common_amenities,mean_embedding
0,27262,t,"['email', 'phone']",100%,ΑΜΠΕΛΟΚΗΠΟΙ,37.98924,23.76500,Entire rental unit,Entire home/apt,2,...,0.0,17.0,"[""Heating - split type ductless system"", ""Dish...","['OTHER', 'OTHER', 'OTHER', 'OTHER', 'Refriger...",37,25,True,False,9,[-6.15361333e-02 -5.01407236e-02 -3.76954190e-...
1,809874,f,"['email', 'phone']",96%,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,37.96215,23.72179,Entire rental unit,Entire home/apt,4,...,0.0,82.0,"[""Host greets you"", ""Dishes and silverware"", ""...","['OTHER', 'OTHER', 'Washer', 'TV', 'OTHER', 'R...",21,12,True,True,7,[-5.95615655e-02 -3.39257978e-02 -3.55266146e-...
2,866381,t,"['email', 'phone', 'work_email']",97%,ΝΕΟΣ ΚΟΣΜΟΣ,37.95523,23.72443,Entire condo,Entire home/apt,3,...,0.0,31.0,"[""Coffee"", ""Dishes and silverware"", ""Washer"", ...","['Coffee maker', 'OTHER', 'Washer', 'Condition...",49,29,True,True,12,[-5.62126637e-02 -3.99859361e-02 -3.53127755e-...
3,886724,f,['email'],0%,ΚΥΨΕΛΗ,37.99745,23.73973,Entire rental unit,Entire home/apt,2,...,1.0,16.0,"[""Host greets you"", ""Luggage dropoff allowed"",...","['OTHER', 'OTHER', 'Washer', 'OTHER', 'OTHER',...",20,13,True,True,6,[-5.84196560e-02 -4.62852195e-02 -3.04865874e-...
4,896212,t,"['email', 'phone']",100%,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,37.98844,23.73845,Entire rental unit,Entire home/apt,2,...,3.0,420.0,"[""Host greets you"", ""Coffee"", ""Dishes and silv...","['OTHER', 'Coffee maker', 'OTHER', 'OTHER', 'O...",45,31,True,True,9,[-5.81393391e-02 -4.77810428e-02 -4.26256545e-...

In [19]:
# how to drop target column with NaN?
final_df = final_df.dropna(subset=['target'])

In [20]:
# changing price to a numerical value
final_df['price'] = final_df['price'].replace('[\$,]', '', regex=True).astype(float)

In [21]:
# droppin unnecesery columns
final_df.drop(columns=['listing_id_x', 'listing_id_y'], inplace=True)

In [22]:
# changing host_avaialbility_rate to a number
final_df['host_acceptance_rate'] = final_df['host_acceptance_rate'].replace('[\%,]', '', regex=True).astype(float)

### Statystyki ostatecznego datasetu

In [23]:
final_df_numerical_columns = final_df.select_dtypes(include=[np.number, np.bool]).columns.tolist()
final_df_categorical_columns = final_df.select_dtypes(exclude=[np.number, np.bool]).columns.tolist()

print("Numerical columns: ", final_df_numerical_columns)
print("Categorical columns: ", final_df_categorical_columns)

Numerical columns:  ['id', 'host_acceptance_rate', 'latitude', 'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month', 'availability_eoy', 'number_of_reviews_ly', 'total_bookings', 'total_reviews', 'total_english_reviews', 'count_negative_english', 'count_positive_english', 'num_of_amenities', 'num_of_other_amenities', 'has_wifi', 'has_air_conditioning', 'num_of_top_10_common_amenities']
Categorical columns:  ['host_is_superhost', 'host_verifications', 'neighbourhood_cleansed', 'property_type', 'room_type', 'bathrooms_text', 'license', 'instant_bookable', 'target', 'amenities', 'standardized_amenities', 'mean_embedding']

In [100]:
final_df.shape

(28807, 41)

# Dataframe'y pod konkretne modele - wstępne sprawdzenie

### Wersja 2 - One Hot Encoding

In [101]:
final_df_ohe = final_df.copy()

In [102]:
final_df_ohe.drop(
    columns=['id', 'mean_embedding', 'listing_id_x', 'listing_id_y', 'amenities', 'standardized_amenities', 'neighbourhood_cleansed', 'license'],
    inplace=True,
    errors='ignore'
)
final_df_ohe.head()

,host_is_superhost,host_verifications,host_acceptance_rate,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,target,total_reviews,total_english_reviews,count_negative_english,count_positive_english,num_of_amenities,num_of_other_amenities,has_wifi,has_air_conditioning,num_of_top_10_common_amenities
0,t,"['email', 'phone']",100.0,37.98924,23.76500,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,short,29.0,17.0,0.0,17.0,37,25,True,False,9
1,f,"['email', 'phone']",96.0,37.96215,23.72179,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,short,97.0,82.0,0.0,82.0,21,12,True,True,7
2,t,"['email', 'phone', 'work_email']",97.0,37.95523,23.72443,Entire condo,Entire home/apt,3,1.0,1 bath,...,long,40.0,31.0,0.0,31.0,49,29,True,True,12
3,f,['email'],0.0,37.99745,23.73973,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,short,18.0,17.0,1.0,16.0,20,13,True,True,6
4,t,"['email', 'phone']",100.0,37.98844,23.73845,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,long,515.0,423.0,3.0,420.0,45,31,True,True,9

In [103]:
non_numerical_columns = final_df_ohe.select_dtypes(include=['object', 'category']).columns
non_numerical_columns = non_numerical_columns.drop('target')
print(non_numerical_columns)

Index(['host_is_superhost', 'host_verifications', 'property_type', 'room_type',
       'bathrooms_text', 'instant_bookable'],
      dtype='object')

In [104]:
# one_hot_encoding
ohe_df = pd.get_dummies(final_df_ohe, columns=non_numerical_columns)

In [105]:
# dropping them as they contain a lot of missing values
ohe_df.drop(columns=['availability_eoy', 'number_of_reviews_ly'], inplace=True)

In [106]:
# filling missin values with 0 -> later we need to find a better solution for missing values
ohe_df = ohe_df.fillna(0)

In [107]:
ohe_df.shape

(28807, 140)

### Wersja 3 - Embeddingi

In [61]:
embeddings = final_df.copy()

In [62]:
embeddings = embeddings.drop(columns=['availability_eoy','number_of_reviews_ly', 'id', 'amenities', 'standardized_amenities'])
embeddings = embeddings.fillna(0)

In [64]:
emb_categorical_columns = embeddings.select_dtypes(include=['object', 'category']).columns
# delete target column from categorical columns
emb_categorical_columns = emb_categorical_columns.drop('target')
print(emb_categorical_columns)

Index(['host_is_superhost', 'host_verifications', 'neighbourhood_cleansed',
       'property_type', 'room_type', 'bathrooms_text', 'license',
       'instant_bookable', 'mean_embedding'],
      dtype='object')

In [65]:
emb_numerical_columns = embeddings.select_dtypes(include=['number']).columns
print(emb_numerical_columns)

Index(['host_acceptance_rate', 'latitude', 'longitude', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'price', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'reviews_per_month',
       'total_bookings', 'total_reviews', 'total_english_reviews',
       'count_negative_english', 'count_positive_english', 'num_of_amenities',
       'num_of_other_amenities', 'num_of_top_10_common_amenities'],
      dtype='object')

In [ ]:
if isinstance(emb_categorical_columns, pd.Index):
    print("emb_categorical_columns is a pandas Index. Converting to list.")
    emb_categorical_columns = emb_categorical_columns.tolist()

emb_categorical_columns is a pandas Index. Converting to list.

In [ ]:
embedding_sizes = [
    (len(embeddings[col].astype('category').cat.categories), min(50, (len(embeddings[col].astype('category').cat.categories) + 1) // 2))
    for col in emb_categorical_columns
]

## XGBoost - OHE

In [84]:
final_df_ohe.head(5)

,host_is_superhost,host_verifications,host_acceptance_rate,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,...,target,total_reviews,total_english_reviews,count_negative_english,count_positive_english,num_of_amenities,num_of_other_amenities,has_wifi,has_air_conditioning,num_of_top_10_common_amenities
0,t,"['email', 'phone']",100.0,37.98924,23.76500,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,short,29.0,17.0,0.0,17.0,37,25,True,False,9
1,f,"['email', 'phone']",96.0,37.96215,23.72179,Entire rental unit,Entire home/apt,4,1.0,1 bath,...,short,97.0,82.0,0.0,82.0,21,12,True,True,7
2,t,"['email', 'phone', 'work_email']",97.0,37.95523,23.72443,Entire condo,Entire home/apt,3,1.0,1 bath,...,long,40.0,31.0,0.0,31.0,49,29,True,True,12
3,f,['email'],0.0,37.99745,23.73973,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,short,18.0,17.0,1.0,16.0,20,13,True,True,6
4,t,"['email', 'phone']",100.0,37.98844,23.73845,Entire rental unit,Entire home/apt,2,1.0,1 bath,...,long,515.0,423.0,3.0,420.0,45,31,True,True,9

In [87]:
ohe_df = pd.get_dummies(final_df_ohe, columns=non_numerical_columns)
ohe_df["target"].head(5)

0    short
1    short
2     long
3    short
4     long
Name: target, dtype: object

In [ ]:
df_cleaned = clean_column_names(ohe_df)
df_cleaned.head(5)